spring:
  application.name: rango-core

  config:
    import:
      - classpath:/application-observability.yml
      - classpath:/application-database.yml

  output.ansi.enabled: always
  docker.compose.file: "app-compose.yaml"
